name: movie-dashboard
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.12.12=h716150d_1
  - setuptools=80.9.0=py312haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - altair==6.0.0
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.4
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - dacite==1.9.2
      - datetime==6.0
      - frozenlist==1.8.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - idna==3.11
      - jinja2==3.1.6
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - markupsafe==3.0.3
      - multidict==6.7.0
      - narwhals==2.15.0
      - numpy==2.4.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.1.0
      - propcache==0.4.1
      - protobuf==6.33.2
      - pyarrow==22.0.0
      - pydeck==0.9.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.30.0
      - six==1.17.0
      - smmap==5.0.2
      - streamlit==1.52.2
      - streamlit-antd-components==0.3.2
      - tenacity==9.1.2
      - themoviedb==1.0.2
      - toml==0.10.2
      - tornado==6.5.4
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.3
      - watchdog==6.0.0
      - yarl==1.22.0
      - zope-interface==8.1.1
prefix: C:\Users\lukeo\.conda\envs\movie-dashboard
